CWL Tool Descriptions (& other work)
carpentries-incubator/cwl-novice-tutorial pull request #44
Opened 2021-09-22 16:06 UTC by douglowe

This PR includes a few changes:

- removal of some episodes which have moved to the intermediate lesson
- added some setup text for installing cwl
- started the introductionary material
- code blocks added for teaching about Tool Descriptions

The Tool Description material is currently written as a simple 'hello world' example - we should replace this with a similar level complexity domain example, but the general layout of the lesson itself I think can remain the same.

2021-09-27 08:57 UTC, mr-c commented
@douglowe Shall I review your PR during this afternoon's monthly curriculum meetup?

2021-09-27 13:06 UTC, douglowe commented
> @douglowe Shall I review your PR during this afternoon's monthly curriculum meetup?

that would be good - I'll pop online now.

2021-09-27 13:58 UTC, mr-c requested changes
Domain examples (even if we will change them later) are welcome!

2021-09-27 13:58 UTC, mr-c commented on _episodes/01-introduction.md
> +
Add a footnote saying that some of this text is from

> Michael R. Crusoe, Sanne Abeln, Alexandru Iosup, Peter Amstutz, John Chilton, Nebojša Tijanić, Hervé Ménager, Stian Soiland-Reyes, Bogdan Gavrilović, Carole Goble, The CWL Community (2021):
Methods Included: Standardizing Computational Reuse and Portability with the Common Workflow Language.
Communication of the ACM. https://doi.org/10.1145/3486897 Retrieved from arXiv 2105.07028 [cs.DC] https://arxiv.org/abs/2105.07028

2021-09-27 13:58 UTC, mr-c commented on _episodes/02-shell_to_cwl.md
> +INFO .../cwl-runner 3.0.20200807132242
Maybe remove this line? Or otherwise remove the version number?

2021-09-27 13:58 UTC, mr-c commented on _episodes/02-shell_to_cwl.md
> +`cwl-runner` has noted that we are missing an `inputs` field, so we will add this also to our script (again as an empty list):
`s/cwl-runner/cwltool/g`

2021-09-27 13:58 UTC, mr-c commented on index.md
>    - define environment variables necessary for execution
environment variables might be a better fit for the intermediate lesson

2021-09-27 13:58 UTC, mr-c commented on _episodes/02-shell_to_cwl.md
> +# "identify tasks, and data links in a script"
Can we have a companion PR against the intermediate repo that moves stuff over?

And then you can delete lines instead commenting them out

2021-09-27 14:02 UTC, mr-c commented
@hmenager can you also review?

2021-11-16 13:09 UTC, mr-c approved these changes
Approving and merging so that @aluesink can implement them in follow-up PRs

2021-11-19 17:42 UTC, merged