Changes to episodes 3 and 4
carpentries-incubator/cwl-novice-tutorial pull request #55
Opened 2021-11-30 16:42 UTC by ALuesink

Work in progress

2021-12-02 11:02 UTC, mr-c requested changes
Just a review on episode 3; waiting for additional episode 4 changes to come in before reviewing (as requested)

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +In the previous episode a single step workflow was shown. To make a multi-step workflow, you extend the `steps` field.
```suggestion
In the previous episode a single step workflow was shown. To make a multi-step workflow, you add more entries to the `steps` field.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +The next 2 steps are alingment of the reads and indexing the alignment. In this example `STAR` and `samtools` are used for these tasks.
```suggestion
In this episode, the workflow is extended with the next two steps of the RNA-sequencing analysis.
The next two steps are alignment of the reads and indexing the alignments. We will be using the `STAR` and `samtools` tools for these tasks.
```
And please add links to the STAR & samtools entries on https://bio.tools

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +	outputSource: index_alignment/bam_sorted_indexed
```suggestion
outputs: 
  qc_html:
    type: File
    outputSource: quality_control/html_file
  bam_sorted_indexed:
    type: File
    outputSource: index_alignment/bam_sorted_indexed
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +	    ramMin: 9000
```suggestion
    requirements:
	    ResourceRequirement:
	      ramMin: 9000
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +The `mapping_reads` step needs some extra information which are command line arguments if you run the STAR aligner on the command line.
```suggestion
The `mapping_reads` step needs some extra information beyond the inputs from the other steps, which is done by providing `default` values. If you want, you can read the `bio-cwl-tools/STAR/STAR-Align.cwl` file to see how these extra inputs are transformed into command line options to the `STAR` program.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +In the `requirements` field the `ResourceRequirement` field allocates a minimum of 9000 MB of RAM.
```suggestion
This information is provided in the `in` field.

To run the tool better, it needs more RAM than the default. So there is a `requirements` entry inside the `mapping_reads` step definition with a `ResourceRequirement` to allocate a minimum of 9000 MiB of RAM.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +This is added in the `inputs` field and in the YAML input file, `workflow_input.yml`.
```suggestion
The newly added `mapping_reads` step also need an input not provided by any of our other steps, therefore an additional workflow-level input is added: a directory that contains the reference genome necessary for the mapping.

This `ref_genome` is added in the `inputs` field of the workflow and in the YAML input file, `workflow_input.yml`.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +A workflow is actually a directed acyclic graph (DAG). This means that the workflow has a certain direction, from inputs to outputs, and has no cycles.
```suggestion
A CWL workflow is a directed acyclic graph (DAG). This means that
1) The workflow has a certain direction, from workflow inputs to step inputs, from step outputs to other step inputs, and from step outputs to workflow outputs
and
2) The workflow definition has no cycles.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +A CWL workflow is a dependency graph. Each step in the workflow depends on either an input or another step.
```suggestion
A CWL workflow is a dependency graph. Each input for a step in the workflow depends on either a workflow-level input or a particular output from another step.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +The resulting SVG file displays the same graph as the one in the cwlviewer. The SVG file can be opened in a internetbrowser and in [Inkscape](https://inkscape.org/)
```suggestion
The resulting SVG file displays the same graph as the one in the cwlviewer. The SVG file can be opened in any web browser and in [Inkscape](https://inkscape.org/), for example.
```

2021-12-02 11:02 UTC, mr-c commented on _episodes/03-dependency_graphs.md
> +The next 2 steps are alingment of the reads and indexing the alignment. In this example `STAR` and `samtools` are used for these tasks.
https://bio.tools/star
https://bio.tools/samtools

2021-12-02 14:14 UTC, mr-c requested changes
Thanks!

2021-12-02 14:14 UTC, mr-c commented on _episodes/04-reusing_tools.md
> +The last step of our workflow is counting the RNA-seq reads for which we will use the [`featureCounts`](https://bio.tools/featurecounts) tool.
```suggestion
The last step of our workflow is counting the RNA-seq reads for which we will use the [`featureCounts`](https://bio.tools/featurecounts) tool.
```

2021-12-02 14:14 UTC, mr-c commented on _episodes/04-reusing_tools.md
> +The screenshot below shows where you can find this button.
```suggestion
After finding the `featureCounts` tool, we need to download the tool to the directory in which our workflow is located.
To download the tool, we go to the `featureCounts.cwl` GitHub page and open the raw file. 
The screenshot below shows where you can find this button.
```

2021-12-02 14:14 UTC, mr-c commented on _episodes/04-reusing_tools.md
> +!{}({{page.root}}/fig/screenshot_featureCounts_tool.png)
This didn't work for me at https://deploy-preview-55--thirsty-hoover-1e0704.netlify.app/04-reusing_tools/index.html

2021-12-02 14:14 UTC, mr-c commented on _episodes/04-reusing_tools.md
> +> >	        ramMin: 9000
```suggestion
> >     requirements:
> >       ResourceRequirement:
> >         ramMin: 9000
```

removing more tabs

2021-12-02 14:14 UTC, mr-c commented on _episodes/04-reusing_tools.md
> +> > The output of this tool is a file called `featurecounts` (line 21).
```suggestion
> > The `featureCounts` CWL document can be found at https://github.com/common-workflow-library/bio-cwl-tools/blob/release/subread/featureCounts.cwl ; it has 2 inputs: `annotations` (line 6) and `mapped_reads`, both files. These inputs can be found on lines 6 and 9.
> > The output of this tool is a file called `featurecounts` (line 21).
```

2021-12-02 14:41 UTC, ALuesink commented on _episodes/04-reusing_tools.md
> +!{}({{page.root}}/fig/screenshot_featureCounts_tool.png)
Finally fixed in commit https://github.com/carpentries-incubator/cwl-novice-tutorial/pull/55/commits/028de017081dc5e0daa7adbc5c8e8ed11f305a20

2021-12-03 10:22 UTC, mr-c approved these changes

2021-12-03 10:24 UTC, merged